#include "stdafx.h"
#include "info.h"

const std::string_view info_str = "                 Welcome to Zork!\n\n"
"You are near a large dungeon, which is reputed to\n"
"contain vast quantities of treasure.  Naturally,\n"
"you wish to acquire some of it. In order to do so,\n"
"you must of course remove it from the dungeon.  To\n"
"receive full credit for it, you must deposit it\n"
"safely in the trophy case in the living room of\n"
"the house.\n\n"
"In addition to valuables, the dungeon contains\n"
"various objects which may or may not be useful in\n"
"your attempt to get rich.  You may need sources of\n"
"light, since dungeons are often dark, and weapons,\n"
"since dungeons often have unfriendly things\n"
"wandering about.  Reading material is scattered\n"
"around the dungeon as well;  some of it is rumored\n"
"to be useful.\n\n"
"To determine how successful you have been, a score\n"
"is kept.  When you find a valuable object and pick\n"
"it up, you receive a certain number of points,\n"
"which depends on the difficulty of finding the\n"
"object.  You receive extra points for transporting\n"
"the treasure safely to the living room and placing\n"
"it in the trophy case.  In addition, some\n"
"particularly interesting rooms have a value\n"
"associated with visiting them. The only penalty is\n"
"for getting yourself killed, which you may do only\n"
"twice.\n\n"
"Of special note is a thief (always carrying a\n"
"large bag) who likes to wander around in the\n"
"dungeon (he has never been seen by the light of\n"
"day).  He likes to take things.  Since he steals\n"
"for pleasure rather than profit and is somewhat\n"
"sadistic, he only takes things which you have\n"
"seen.  Although he prefers valuables, sometimes in\n"
"his haste he may take something which is worth-\n"
"less. From time to time, he examines his take and\n"
"discards objects which he doesn't like. He may\n"
"occasionally stop in a room you are visiting, but\n"
"more often he just wanders through and rips you\n"
"off (he is a skilled pickpocket).\n";

const std::string_view help_str =
{
"Useful commands:\n\n"
"  The 'BRIEF' command suppresses printing of long\n"
"    room descriptions for rooms which have been\n"
"    visited.\n"
"  The 'SUPERBRIEF' command suppresses printing of\n"
"    long room descriptions for all rooms.\n"
"  The 'VERBOSE' command restores long descriptions.\n"
"  The 'INFO' command prints information which might\n"
"    give some idea of what the game is about.\n"
"  The 'QUIT' command prints your score and asks\n"
"    whether you wish to continue playing.\n"
"  The 'SAVE' command saves the state of the game\n"
"    for later continuation.\n"
"  The 'RESTORE' command restores a saved game.\n"
"  The 'INVENTORY' command lists the objects in\n"
"    your possession.\n"
"  The 'LOOK' command prints a description of your\n"
"    surroundings.\n"
"  The 'SCORE' command prints your current score\n"
"    and ranking.\n"
"  The 'TIME' command tells you how long you have\n"
"    been playing.\n"
"  The 'DIAGNOSE' command reports on your injuries,\n"
"    if any.\n\n"
"Command abbreviations:\n"
"   The 'INVENTORY' command may be abbreviated 'I'.\n"
"   The 'LOOK' command may be abbreviated 'L'.\n"
"   The 'QUIT' command may be abbreviated 'Q'. \n\n"
"Containment:\n"
"  Some objects can contain other objects.  Many\n"
"such containers can be opened and closed.  The\n"
"rest are always open.  They may or may not be\n"
"transparent.  For you to access (e.g., take) an\n"
"object which is in a container, the container must\n"
"be open.  For you to see such an object, the\n"
"container must be either open or transparent.\n"
"  Containers have a capacity, and objects have\n"
"sizes; the number of objects which will fit\n"
"therefore depends on their sizes.  You may put any\n"
"object you have access to (it need not be in your\n"
"hands) into any other object.  At some point, the\n"
"program will attempt to pick it up if you don't\n"
"already have it, which process may fail if you're\n"
"carrying too much. Although containers can contain\n"
"other containers, the program doesn't access more\n"
"than one level down.\n\n"
"Fighting:\n"
"  Occupants of the dungeon will, as a rule, fight\n"
"back when attacked. In some cases, they may attack\n"
"even if unprovoked.\n\n"
"Useful verbs here are:\n"
"  'ATTACK <villain> WITH <weapon>', 'KILL', etc.\n"
"Knife - throwing may or may not be useful.  You\n"
"have a fighting strength which varies with time.\n"
"Being in a fight, getting killed, and being\n"
"injured all lower this strength.\n"
"Strength is regained with time.  Thus, it is not a\n"
"good idea to fight someone immediately after being\n"
"killed. Other details should become apparent after\n"
"a few melees or deaths.\n\n"
"Command parser:\n"
"  A command is one line of text terminated by a\n"
"carriage return.\n"
"For reasons of simplicity, all words are dist-\n"
"inguished by their first five letters.  All others\n"
"are ignored.  For example, typing 'DISASSEMBLE THE\n"
"ENCYCLOPEDIA' is not only meaningless, it also\n"
"creates excess effort for your fingers.  Note that\n"
"this truncation may produce ambiguities in the\n"
"interpretation of longer words.\n"
"You are dealing with a fairly stupid parser, which\n"
"understands the following types of things--\n\n"
"  Actions:\n"
"    Among the more obvious of these are TAKE, PUT,\n"
"    DROP, etc. Fairly general forms of these may\n"
"    be used, such as PICK UP, PUT DOWN, etc.\n\n"
"  Directions:\n"
"    NORTH, SOUTH, UP, DOWN, etc. and their various\n"
"    abbreviations. Other more obscure directions\n"
"    (LAND, CROSS) are appropriate in only certain\n"
"    situations.\n\n"
"  Objects:\n"
"    Most objects have names and can be referenced\n"
"    by them.\n\n"
"  Adjectives:\n"
"    Some adjectives are understood and required\n"
"    when there are two objects which can be\n"
"    referenced with the same 'name' (e.g., DOORs,\n"
"    BUTTONs).\n\n"
"  Prepositions:\n\n"
"    It may be necessary in some cases to include\n"
"    prepositions, but the parser attempts to\n"
"    handle cases which aren't ambiguous without.\n"
"    Thus 'GIVE CAR TO DEMON' will work, as will\n"
"    'GIVE DEMON CAR'.  'GIVE CAR DEMON' probably\n"
"    won't do anything interesting.\n"
"    When a preposition is used, it should be\n"
"    appropriate;  'GIVE CAR WITH DEMON' won't\n"
"    parse.\n"
"  Sentences:\n\n"
"    The parser understands a reasonable number of\n"
"    syntactic constructions.  In particular,\n"
"    multiple commands (separated by periods) can\n"
"    be placed on the same line.\n\n"
"  Ambiguity:\n"
"    The parser tries to be clever about what to do\n"
"    in the case of actions which require objects\n"
"    that are not explicitly specified.\n"
"    If there is only one possible object, the\n"
"    parser will assume that it should be used.\n"
"    Otherwise, the parser will ask. Most questions\n"
"    asked by the parser can be answered."
};